googleFonts: true
sources:
- NotoSerifTodhri-Regular.designspace
familyName: Noto Serif Todhri
recipeProvider: noto
removeOutlineOverlaps: false
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core

